import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { ScanResult } from '@/types';

export async function exportReport(result: ScanResult): Promise<string> {
  // 1. Create a hidden off-screen div
  const div = document.createElement('div');
  div.id = 'pdf-report-content';
  div.style.position = 'absolute';
  div.style.left = '-9999px';
  div.style.top = '0';
  div.style.width = '800px'; // fixed width for PDF
  div.style.backgroundColor = '#ffffff';
  div.style.color = '#000000';
  div.style.padding = '40px';
  div.style.fontFamily = 'sans-serif';

  // 2. Populate it with a clean HTML layout
  div.innerHTML = `
    <div style="border-bottom: 2px solid #e5e7eb; padding-bottom: 20px; margin-bottom: 30px;">
      <h1 style="margin: 0; font-size: 28px; color: #111827;">FairScan Audit Report</h1>
      <p style="margin: 8px 0 0; color: #6b7280; font-size: 14px;">
        Dataset: ${result.filename} | Rows: ${result.rowCount} | Date: ${new Date().toLocaleDateString()}
      </p>
    </div>

    <div style="display: flex; gap: 20px; margin-bottom: 30px;">
      <div style="flex: 1; padding: 20px; background: #f3f4f6; border-radius: 8px;">
        <div style="font-size: 12px; text-transform: uppercase; color: #6b7280; margin-bottom: 8px;">FairScan Score</div>
        <div style="font-size: 48px; font-weight: bold; color: #111827;">${result.fairscanScore}<span style="font-size: 20px; color: #6b7280;">/100</span></div>
        <div style="margin-top: 8px; display: inline-block; padding: 4px 12px; border-radius: 100px; font-size: 12px; font-weight: bold; background: #fee2e2; color: #991b1b; text-transform: uppercase;">
          ${result.riskLevel} Risk
        </div>
      </div>
      <div style="flex: 2; padding: 20px; background: #f3f4f6; border-radius: 8px;">
        <div style="font-size: 12px; text-transform: uppercase; color: #6b7280; margin-bottom: 8px;">Executive Summary</div>
        <div style="font-size: 16px; font-style: italic; color: #374151; line-height: 1.5;">
          "${result.slices[0]?.impactStory || 'No significant bias detected.'}"
        </div>
      </div>
    </div>

    <h2 style="font-size: 20px; margin: 30px 0 15px;">Top Flagged Slices</h2>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
      <thead>
        <tr style="border-bottom: 1px solid #d1d5db; text-align: left;">
          <th style="padding: 12px 8px; color: #4b5563; font-size: 12px; text-transform: uppercase;">Slice</th>
          <th style="padding: 12px 8px; color: #4b5563; font-size: 12px; text-transform: uppercase;">Metric</th>
          <th style="padding: 12px 8px; color: #4b5563; font-size: 12px; text-transform: uppercase; text-align: right;">Value</th>
          <th style="padding: 12px 8px; color: #4b5563; font-size: 12px; text-transform: uppercase; text-align: right;">Severity</th>
        </tr>
      </thead>
      <tbody>
        ${result.slices.slice(0, 5).map(s => `
          <tr style="border-bottom: 1px solid #e5e7eb;">
            <td style="padding: 12px 8px; font-weight: 500;">${s.groupLabel}</td>
            <td style="padding: 12px 8px; color: #6b7280;">${s.worstMetric.metricName}</td>
            <td style="padding: 12px 8px; font-family: monospace; text-align: right;">${s.worstMetric.value.toFixed(2)}</td>
            <td style="padding: 12px 8px; text-align: right; text-transform: capitalize; color: ${s.severity === 'critical' ? '#dc2626' : '#ea580c'};">${s.severity}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <h2 style="font-size: 20px; margin: 30px 0 15px;">AI Explanations</h2>
    <div style="margin-bottom: 30px;">
      ${result.slices.slice(0, 3).filter(s => s.explanation).map(s => `
        <div style="margin-bottom: 16px; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px;">
          <div style="font-weight: bold; margin-bottom: 8px;">${s.groupLabel} <span style="font-weight: normal; color: #6b7280; font-size: 14px;">(${s.biasType})</span></div>
          <div style="color: #374151; line-height: 1.5; font-size: 14px;">${s.explanation}</div>
        </div>
      `).join('')}
    </div>

    <h2 style="font-size: 20px; margin: 30px 0 15px;">Fix Recommendations</h2>
    <div>
      ${(result.slices[0]?.fixes || []).slice(0, 3).map((f, i) => `
        <div style="margin-bottom: 16px;">
          <div style="font-weight: bold; font-size: 15px; margin-bottom: 4px;">${i+1}. ${f.title}</div>
          <div style="color: #4b5563; font-size: 14px;">${f.description}</div>
        </div>
      `).join('')}
    </div>

    <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px;">
      Generated by FairScan · Powered by Gemini 2.5 Flash · ${new Date().toLocaleDateString()}
    </div>
  `;

  document.body.appendChild(div);

  try {
    // 3. Use html2canvas
    const canvas = await html2canvas(div, { scale: 2 });
    
    // 4. Use jsPDF
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    
    // 5. Save
    const pdfBase64 = pdf.output('datauristring').split(',')[1];
    pdf.save(`FairScan_Report_${result.filename.replace('.csv', '')}_${new Date().toISOString().split('T')[0]}.pdf`);
    return pdfBase64;
  } finally {
    // 6. Remove div
    document.body.removeChild(div);
  }
}
