import {
  ShieldCheck,
  Zap,
  BarChart3,
  Brain,
  FileDown,
  ArrowRight,
} from "lucide-react";
import { DotGridBackground } from "@/components/DotGridBackground";

interface LandingViewProps {
  onStart: () => void;
}

export function LandingView({ onStart }: LandingViewProps) {
  return (
    <div className="relative min-h-screen overflow-hidden bg-bg">
      <DotGridBackground />

      <header className="relative z-10 flex h-16 items-center justify-between px-6 md:px-10">
        <div className="flex items-center gap-2">
          <ShieldCheck size={20} className="text-brand" strokeWidth={2.25} />
          <span className="text-[18px] font-semibold tracking-tight text-text-primary">
            FairScan
          </span>
        </div>
        <nav className="flex items-center gap-5">
          <a
            href="#how"
            className="hidden text-sm text-text-secondary transition-colors hover:text-text-primary md:block"
          >
            How it works
          </a>
          <a
            href="#"
            className="hidden text-sm text-text-secondary transition-colors hover:text-text-primary md:block"
          >
            GitHub
          </a>
          <button
            type="button"
            onClick={onStart}
            className="inline-flex items-center gap-1 rounded-md bg-brand px-3.5 py-1.5 text-sm font-medium text-white transition-opacity hover:opacity-90"
          >
            Start Auditing <ArrowRight size={14} />
          </button>
        </nav>
      </header>

      <main className="relative z-10 mx-auto max-w-6xl px-6 pb-24 pt-16 md:pt-24">
        <div className="flex flex-col items-center text-center">
          <div className="mb-8 inline-flex items-center gap-1.5 rounded-full border border-brand/40 bg-brand-glow px-3 py-1 text-[13px] text-brand">
            <Zap size={13} className="fill-brand" strokeWidth={2} />
            Powered by Gemini 2.5 Flash
          </div>

          <h1 className="font-display text-[44px] leading-[1.05] text-text-primary md:text-[64px]">
            Bias lives in your data.
            <br />
            FairScan finds it.
          </h1>

          <p className="mt-6 max-w-[520px] text-[18px] leading-relaxed text-text-secondary">
            Upload a dataset, configure your sensitive attributes, and get a
            scored, explainable fairness audit in under 10 seconds.
          </p>

          <div className="mt-10 flex flex-col items-stretch gap-3 sm:flex-row">
            <button
              type="button"
              onClick={onStart}
              className="inline-flex h-12 items-center justify-center rounded-lg bg-brand px-6 text-[15px] font-medium text-white transition-opacity hover:opacity-90"
            >
              Upload a CSV
            </button>
            <button
              type="button"
              onClick={onStart}
              className="inline-flex h-12 items-center justify-center rounded-lg border border-border-2 bg-surface px-6 text-[15px] font-medium text-text-primary transition-colors hover:border-brand"
            >
              Paste model description
            </button>
          </div>
        </div>

        <div
          id="how"
          className="mx-auto mt-20 grid max-w-[900px] gap-4 md:grid-cols-3"
        >
          <FeatureCard
            Icon={BarChart3}
            title="Fairness Metrics Engine"
            body="Computes demographic parity, disparate impact, equalized odds, and representation imbalance across all sensitive groups."
          />
          <FeatureCard
            Icon={Brain}
            title="Gemini-Powered Explanations"
            body="Every flagged slice gets a plain-English explanation and 3 actionable fix recommendations generated by Gemini AI."
          />
          <FeatureCard
            Icon={FileDown}
            title="One-Click PDF Export"
            body="Export a consulting-grade fairness report with charts, score, and recommendations. No server. No data leaves your browser."
          />
        </div>

        <div className="mt-16 flex flex-wrap items-center justify-center gap-x-2 gap-y-1 text-[13px] text-text-dim">
          <span>100% browser-side</span>
          <span aria-hidden>·</span>
          <span>Zero data uploaded</span>
          <span aria-hidden>·</span>
          <span>Free forever</span>
          <span aria-hidden>·</span>
          <span>Gemini 2.5 Flash</span>
        </div>
      </main>
    </div>
  );
}

function FeatureCard({
  Icon,
  title,
  body,
}: {
  Icon: typeof BarChart3;
  title: string;
  body: string;
}) {
  return (
    <div className="rounded-xl border border-border bg-surface p-6 card-glow">
      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-surface-2">
        <Icon size={18} className="text-brand" strokeWidth={2} />
      </div>
      <h3 className="mt-4 text-[15px] font-medium text-text-primary">
        {title}
      </h3>
      <p className="mt-2 text-[13px] leading-relaxed text-text-secondary">
        {body}
      </p>
    </div>
  );
}
